micronaut:
  server:
    netty:
      access-logger:
        enabled: true
        logger-name: ACCESS_LOG
        log-format: 'remote=%h request="%r" status=%s bytes=%b durationMicros=%D'
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins:
            - http://localhost:3001
            - http://127.0.0.1:3001
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - Content-Type
            - Authorization
            - Accept
            - Origin
